name: production

services:
  frontend:
    image: yyassif/ragmind-frontend:latest
    pull_policy: if_not_present
    container_name: web
    restart: always
    environment:
      - NEXT_PUBLIC_ENV={NEXT_PUBLIC_ENV}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_AUTH_MODES=${NEXT_PUBLIC_AUTH_MODES}
    depends_on:
      - backend-core
    ports:
      - 3000:3000

  backend-core:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: backend-core
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5050/healthz" ]
    command:
      - "uvicorn"
      - "ragmind_api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
    ports:
      - 5050:5050

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  worker:
    pull_policy: if_not_present
    image: yyassif/ragmind-backend:latest
    container_name: worker
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker worker -l info
    depends_on:
      - redis

  beat:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: beat
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker beat -l info
    depends_on:
      - redis

  flower:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: flower
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker flower -l info --port=5555
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555

networks:
  ragmind-network:
    driver: bridge
