name: production

services:
  frontend:
    image: yyassif/ragmind-frontend:latest
    pull_policy: if_not_present
    container_name: web
    restart: always
    environment:
      - NEXT_PUBLIC_ENV={NEXT_PUBLIC_ENV}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_AUTH_MODES=${NEXT_PUBLIC_AUTH_MODES}
    depends_on:
      - backend-core
    ports:
      - 3000:3000

  backend-core:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: backend-core
    restart: always
    environment:
      - DEV_MODE=${DEV_MODE}
      - AUTHENTICATE=${AUTHENTICATE}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PG_DATABASE_ASYNC_URL=${PG_DATABASE_ASYNC_URL}
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELEBRY_BROKER_QUEUE_NAME=${CELEBRY_BROKER_QUEUE_NAME}
      - CI_TEST_API_KEY=${CI_TEST_API_KEY}
      - TELEMETRY_URL=${TELEMETRY_URL}
      - APPLICATION_DOMAIN=${APPLICATION_DOMAIN}
      - BACKEND_URL=${BACKEND_URL}
      - AWS_ARN_KEY_ID=${AWS_ARN_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_ADDRESS=${RESEND_EMAIL_ADDRESS}
      - RESEND_CONTACT_SALES_FROM=${RESEND_CONTACT_SALES_FROM}
      - RESEND_CONTACT_SALES_TO=${RESEND_CONTACT_SALES_TO}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_CERT_URL=${GOOGLE_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_JAVASCRIPT_ORIGINS=${GOOGLE_JAVASCRIPT_ORIGINS}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SHAREPOINT_CLIENT_ID=${SHAREPOINT_CLIENT_ID}
      - CRAWL_DEPTH=${CRAWL_DEPTH}
      - PROJECT_ID=${PROJECT_ID}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5050/healthz" ]
    command:
      - "uvicorn"
      - "ragmind_api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
    ports:
      - 5050:5050

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  worker:
    pull_policy: if_not_present
    image: yyassif/ragmind-backend:latest
    container_name: worker
    restart: always
    environment:
      - DEV_MODE=${DEV_MODE}
      - AUTHENTICATE=${AUTHENTICATE}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PG_DATABASE_ASYNC_URL=${PG_DATABASE_ASYNC_URL}
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELEBRY_BROKER_QUEUE_NAME=${CELEBRY_BROKER_QUEUE_NAME}
      - CI_TEST_API_KEY=${CI_TEST_API_KEY}
      - TELEMETRY_URL=${TELEMETRY_URL}
      - APPLICATION_DOMAIN=${APPLICATION_DOMAIN}
      - BACKEND_URL=${BACKEND_URL}
      - AWS_ARN_KEY_ID=${AWS_ARN_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_ADDRESS=${RESEND_EMAIL_ADDRESS}
      - RESEND_CONTACT_SALES_FROM=${RESEND_CONTACT_SALES_FROM}
      - RESEND_CONTACT_SALES_TO=${RESEND_CONTACT_SALES_TO}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_CERT_URL=${GOOGLE_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_JAVASCRIPT_ORIGINS=${GOOGLE_JAVASCRIPT_ORIGINS}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SHAREPOINT_CLIENT_ID=${SHAREPOINT_CLIENT_ID}
      - CRAWL_DEPTH=${CRAWL_DEPTH}
      - PROJECT_ID=${PROJECT_ID}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker worker -l info
    depends_on:
      - redis

  beat:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: beat
    restart: always
    environment:
      - DEV_MODE=${DEV_MODE}
      - AUTHENTICATE=${AUTHENTICATE}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PG_DATABASE_ASYNC_URL=${PG_DATABASE_ASYNC_URL}
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELEBRY_BROKER_QUEUE_NAME=${CELEBRY_BROKER_QUEUE_NAME}
      - CI_TEST_API_KEY=${CI_TEST_API_KEY}
      - TELEMETRY_URL=${TELEMETRY_URL}
      - APPLICATION_DOMAIN=${APPLICATION_DOMAIN}
      - BACKEND_URL=${BACKEND_URL}
      - AWS_ARN_KEY_ID=${AWS_ARN_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_ADDRESS=${RESEND_EMAIL_ADDRESS}
      - RESEND_CONTACT_SALES_FROM=${RESEND_CONTACT_SALES_FROM}
      - RESEND_CONTACT_SALES_TO=${RESEND_CONTACT_SALES_TO}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_CERT_URL=${GOOGLE_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_JAVASCRIPT_ORIGINS=${GOOGLE_JAVASCRIPT_ORIGINS}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SHAREPOINT_CLIENT_ID=${SHAREPOINT_CLIENT_ID}
      - CRAWL_DEPTH=${CRAWL_DEPTH}
      - PROJECT_ID=${PROJECT_ID}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker beat -l info
    depends_on:
      - redis

  flower:
    image: yyassif/ragmind-backend:latest
    pull_policy: if_not_present
    container_name: flower
    restart: always
    environment:
      - DEV_MODE=${DEV_MODE}
      - AUTHENTICATE=${AUTHENTICATE}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PG_DATABASE_ASYNC_URL=${PG_DATABASE_ASYNC_URL}
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELEBRY_BROKER_QUEUE_NAME=${CELEBRY_BROKER_QUEUE_NAME}
      - CI_TEST_API_KEY=${CI_TEST_API_KEY}
      - TELEMETRY_URL=${TELEMETRY_URL}
      - APPLICATION_DOMAIN=${APPLICATION_DOMAIN}
      - BACKEND_URL=${BACKEND_URL}
      - AWS_ARN_KEY_ID=${AWS_ARN_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_ADDRESS=${RESEND_EMAIL_ADDRESS}
      - RESEND_CONTACT_SALES_FROM=${RESEND_CONTACT_SALES_FROM}
      - RESEND_CONTACT_SALES_TO=${RESEND_CONTACT_SALES_TO}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_CERT_URL=${GOOGLE_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_JAVASCRIPT_ORIGINS=${GOOGLE_JAVASCRIPT_ORIGINS}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SHAREPOINT_CLIENT_ID=${SHAREPOINT_CLIENT_ID}
      - CRAWL_DEPTH=${CRAWL_DEPTH}
      - PROJECT_ID=${PROJECT_ID}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A ragmind_api.celery_worker flower -l info --port=5555
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555

networks:
  ragmind-network:
    driver: bridge
