name: Prebuild & Push All Docker Images to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  build_and_push_frontend_image:
    name: Build and Push Frontend Docker Image to DockerHub
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Cache Storage Backend
        run: |
          docker buildx create --use --driver=docker-container

      - name: See the file in the runner
        run: |
          ls -la

      - name: Build, Tag, and Push Image to ghcr.io, Docker Hub.
        id: build-image
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./frontend/
          push: true
          platforms: linux/amd64
          tags: yyassif/ragmind-frontend:latest, yyassif/ragmind-frontend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_and_push_backend_image:
    name: Build and Push Backend Docker Image to DockerHub
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Cache Storage Backend
        run: |
          docker buildx create --use --driver=docker-container

      - name: See the file in the runner
        run: |
          ls -la

      - name: Build, Tag, and Push Image to ghcr.io, Docker Hub.
        id: build-image
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./backend/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: yyassif/ragmind-backend:latest, yyassif/ragmind-backend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
